export const NODE_RADIUS = 0.25;
export const POLICY_ARROW_STROKE_WIDTH = 0.05;
export const POLICY_ARROW_TIP_OFFSET = POLICY_ARROW_STROKE_WIDTH;
export const PATH_ARROW_STROKE_WIDTH = 0.04;
export const PATH_ARROW_TIP_OFFSET = PATH_ARROW_STROKE_WIDTH;
